language: python
python:
  - "2.7"
install:
  - npm install
  - pip install WebTest
before_script:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud version
script:
  - python dist/test_runner.py ~/google_appengine tests/

# SEe http://docs.travis-ci.com/user/deployment/google-app-engine/
#deploy:
#  provider: gae
#  keyfile: "YOUR SERVICE ACCOUNT JSON FILE"
#  default: true
#  project: "YOUR PROJECT ID"
